#!/bin/bash

mkdir -p ~/.docker/cli-plugins \
  && curl \
    --silent \
    --location \
    --output ~/.docker/cli-plugins/docker-buildx \
    https://github.com/docker/buildx/releases/download/v0.2.0/buildx-v0.2.0.linux-amd64 \
  && chmod +x ~/.docker/cli-plugins/docker-buildx

docker buildx create \
  --use \
  --name multiarch

# Register binfmt_misc interpreters
docker run \
  --rm \
  --privileged \
  multiarch/qemu-user-static --reset --persistent yes

docker buildx create \
  --use \
  --name multiarch

docker buildx inspect

