#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled

echo "Running hook: ${0}"

# Register binfmt_misc interpreters
docker run \
  --rm \
  --privileged \
  docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3 

docker buildx create \
  --use \
  --name multiarch
