name: docker-buildx

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: build and publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: info
        run: docker version

      - name: prepare build
        run: hooks/pre_build

      - name: build
        env:
          DOCKERFILE_PATH: Dockerfile
          IMAGE_NAME: 1nfiniteloop/multiarch-example:latest
        run: hooks/build

      - name: docker hub login
        run: docker login --user "${{ secrets.DOCKERHUB_USER }}" --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: push
        env:
          DOCKERFILE_PATH: Dockerfile
          IMAGE_NAME: 1nfiniteloop/multiarch-example:latest
        run: hooks/push

      - name: docker hub logout
        run: docker logout

