name: docker-buildx

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
          echo "github.ref: ${{ github.ref }}"
          docker version

      - name: checkout
        uses: actions/checkout@v1

      - name: prepare build
        run: .github/hooks/pre_build

      - name: docker hub login
        run: docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}"

        # TODO tag docker image with git-tag, if available
      - name: build and push
        env:
          IMAGE_NAME: 1nfiniteloop/multiarch-example:latest
          TARGETS: linux/arm/v7,linux/arm64,linux/amd64
        run: .github/hooks/build

      - name: docker hub logout
        run: docker logout
