name: docker-buildx

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: build and publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare build
        run: hooks/pre_build

      - name: build
        env:
          DOCKERFILE_PATH: Dockerfile
          IMAGE_NAME: 1nfiniteloop/multiarch-example:latest
        run: hooks/build

      - name: push
        run: echo "TODO!"
